// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wutcouirebhutufebeyd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind1dGNvdWlyZWJodXR1ZmViZXlkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ4NjM1NDAsImV4cCI6MjA2MDQzOTU0MH0.bXhLN_NJVZub7HPBfi5HlEXCqnvImz3wJLM-LIQ9hBo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);